<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Fora.Mikro.Win.Form</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Fora.Mikro.Win.Form.dll.licenses" />
    <EmbeddedResource Include="Fora.Mikro.Win.Form.dll.licenses" LogicalName="Fora.Mikro.Win.Form.dll.licenses" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Fora.Mikro">
      <HintPath>..\..\Fora.Mikro.dll</HintPath>
    </Reference>
    <Reference Include="Fora.Mikro.Data.Sql">
      <HintPath>..\..\Fora.Mikro.Data.Sql.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="DevExpress.Utils.v17.1">
      <HintPath>..\..\DevExpress.Utils.v17.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.XtraEditors.v17.1">
      <HintPath>..\..\DevExpress.XtraEditors.v17.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.XtraGrid.v17.1">
      <HintPath>..\..\DevExpress.XtraGrid.v17.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.XtraReports.v17.1">
      <HintPath>..\..\DevExpress.XtraReports.v17.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Data.v17.1">
      <HintPath>..\..\DevExpress.Data.v17.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Printing.v17.1.Core">
      <HintPath>..\..\DevExpress.Printing.v17.1.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>