/*
  Run once as a DBA against the target Mikro SQL Server database.
  The Windows agent never runs DDL. Replace only the explicitly listed table
  names after the agent's V15/V16 preflight reports them as supported.
*/
ALTER DATABASE CURRENT SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 14 DAYS, AUTO_CLEANUP = ON);
GO

ALTER TABLE dbo.CARI_HESAPLAR ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);
ALTER TABLE dbo.STOKLAR ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);
ALTER TABLE dbo.STOK_HAREKETLERI ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);
ALTER TABLE dbo.SIPARISLER ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);
GO
