namespace ErpBridge.CentralApi.Domain;

/// <summary>
/// One parameter Fora declares, with everything the panel needs to show it.
///
/// Fora keeps its defaults inside the application, not in the database: <c>_FORA_PARAMETRELER</c>
/// holds only the rows that differ from the default, and a value set back to its default is
/// deleted. Without this catalogue a stored row says nothing about the effective setting, so the
/// catalogue is the fixed point everything else resolves against.
///
/// Seeded from <c>catalog/parameters/</c>, which is generated by
/// <c>tools/ForaCatalogExtractor</c> from the decompiled Fora sources.
/// </summary>
public sealed class ParameterCatalogEntry
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>Value written to Mikro's <c>ParametreProgram</c> column, e.g. <c>akilli</c>.</summary>
    public string Program { get; set; } = string.Empty;

    /// <summary>
    /// Fora factory that declares this parameter, e.g. <c>MobilKullanici</c>. A program can have
    /// several sets (<c>YaziciAyarlari</c> has page settings and field settings), and parameter
    /// ids are unique only inside a set.
    /// </summary>
    public string CatalogMethod { get; set; } = string.Empty;

    /// <summary>Mikro's <c>ParametreID</c> — the real key. Names are not unique across sets.</summary>
    public int ParametreId { get; set; }

    /// <summary>Mikro's <c>ParametreAdi</c>. Kept for readability and for matching Fora imports.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>The value Fora falls back to when no row exists. Never null; may be empty.</summary>
    public string DefaultValue { get; set; } = string.Empty;

    /// <summary>
    /// Set when the default is supplied at run time rather than being constant — a printer
    /// template field defaults its caption to the field's own name.
    /// </summary>
    public string? DefaultSource { get; set; }

    /// <summary>What the scope value means: <c>MobileUser</c>, <c>PrinterTemplate</c>, <c>None</c>…</summary>
    public string ScopeKind { get; set; } = string.Empty;

    /// <summary>
    /// Addressing columns the caller fills in, as <c>user,altGrubu</c>. Fora is not consistent:
    /// <c>akilli</c> addresses through <c>ParametreUser</c>, the import templates through
    /// <c>ParametreAltGrubu</c>, and a printer template needs both.
    /// </summary>
    public string ScopeFields { get; set; } = string.Empty;

    /// <summary>Constant written to <c>ParametreUser</c> (empty when that column carries the scope).</summary>
    public string User { get; set; } = string.Empty;

    /// <summary>Constant written to <c>ParametreAnaGrubu</c>.</summary>
    public string AnaGrubu { get; set; } = string.Empty;

    /// <summary>Constant written to <c>ParametreAltGrubu</c>.</summary>
    public string AltGrubu { get; set; } = string.Empty;

    /// <summary>
    /// How the panel should render the value: <c>boolean</c>, <c>text</c>, <c>integer</c>,
    /// <c>choice</c>, <c>decimal</c>, <c>reference</c>, <c>color</c>, <c>secret</c>,
    /// <c>composite</c>, <c>multilineText</c>. Null when no Fora editor exposes the parameter.
    /// </summary>
    public string? Editor { get; set; }

    /// <summary>ERP list a <c>reference</c> value is chosen from (<c>depo</c>, <c>cari</c>…).</summary>
    public string? ReferenceKind { get; set; }

    /// <summary>
    /// Why a <c>secret</c> is treated as one: <c>designer</c> when Fora masks the field,
    /// <c>name</c> when only its name says so. Fora leaves some credentials unmasked.
    /// </summary>
    public string? SecretSource { get; set; }

    /// <summary>Wording shown next to the field in Fora, or null when it has no editor.</summary>
    public string? Label { get; set; }

    /// <summary>Tab titles from the outermost inwards, joined with " / ".</summary>
    public string? TabPath { get; set; }

    /// <summary>Reading order inside the editor; null when the parameter has no editor.</summary>
    public int? EditorOrder { get; set; }

    /// <summary>Fixed options for a <c>choice</c> field as JSON, or null.</summary>
    public string? OptionsJson { get; set; }

    /// <summary>
    /// True when this release of Sipariş Cepte actually honours the parameter. Everything starts
    /// false: the panel shows an "inert in this version" badge rather than letting someone change
    /// a setting and wonder why nothing happened (D16).
    /// </summary>
    public bool IsImplemented { get; set; }

    /// <summary>
    /// True when a newer catalogue no longer declares the parameter. Rows are never deleted, so
    /// values stored against a withdrawn parameter are not silently orphaned (D2).
    /// </summary>
    public bool IsDeprecated { get; set; }

    /// <summary>Fora build the catalogue was read from, or "unknown".</summary>
    public string SourceBuild { get; set; } = string.Empty;

    public DateTimeOffset CreatedAtUtc { get; set; } = DateTimeOffset.UtcNow;

    public DateTimeOffset UpdatedAtUtc { get; set; } = DateTimeOffset.UtcNow;
}
